# Use Ubuntu 20.04 LTS as the base image
FROM ubuntu:20.04

# Set environment variables
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

# Install required dependencies
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion

# Install Miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Create the 'analysis' environment and install numpy, scikit-learn, and statsmodels
RUN conda create -n analysis && \
    echo "source activate analysis" >~/.bashrc && \
    /bin/bash -c "source activate analysis && \
    conda install -c anaconda numpy scikit-learn statsmodels"

# Set the ENTRYPOINT to start the 'analysis' environment by default
ENTRYPOINT [ "/bin/bash", "-c", "source activate analysis && exec /bin/bash -i" ]